### ISSUE TITLE
Does not load correctly in ElvUI 12.39

### ISSUE THREAD

**Issue by raptormama** [caderaspindrift/RP_Tags#4]
ElvUI unitframes display the raw tag (e.g. `[rp:name]`) in ElvUI 12.39, but display correctly in 12.38. This affects at least the player frame, party frames, and target frame -- but probably affects all of them.

**Comment by raptormama** [comment]
This commit fixes the issue for me.

**Comment by caderaspindrift** [comment]
Hi, sorry I didn't get back to this. I haven't played WoW in _forever_, and shortly after this issue was posted, I had a seizure caused by a brain tumor. Had brain surgery in September; still on the mend but playing WoW to get my spirits up while recovering.

Thank you so much, jharrell and raptormama!
